import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import { Header } from '@/components/shared/header'
import { Footer } from '@/components/shared/footer'
import { ToasterProvider } from '@/components/providers/toaster'
import { NextAuthSessionProvider } from '@/components/providers/next-auth'
import { CartContextProvider } from '@/context/cart-context'


const poppins = Poppins({ 
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: "--font-sans"
})

export const metadata: Metadata = {
  title: 'Eventfy',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" className="">
      <body className={
        cn(
          "bg-background font-sans antialiased",
          poppins.variable
        )
      }>
        <NextAuthSessionProvider>
          <CartContextProvider>
            {children}
            <ToasterProvider />
          </CartContextProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  )
}
